version: '1.0'
name: pipeline-20230811
displayName: pipeline-20230811
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - gh-pages
stages:
  - name: stage-492e0d0a
    displayName: Pages
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - 'git push https://${USERNAME}:${ACCESS_TOKEN}@gitee.com/${GITEE_REPO} master:gh-pages --force'
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
