version: '1.0'
name: pipeline-20230810
displayName: pipeline-20230810
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - gh-pages
stages:
  - name: stage-e6cbdaf0
    displayName: pages
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
